name: lrf
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  flutter_dotenv: ^5.0.2
  maps_launcher: ^2.0.1
  http: ^0.13.5
  glass: ^1.0.1+1
  animations: ^2.0.3
  expandable: ^5.0.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_dynamic_links: ^4.3.5 
  cloud_firestore: ^3.4.5
  open_location_picker: ^0.2.0
  location: ^4.4.0 
  slide_to_confirm: ^1.1.0 
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  supabase_flutter: ^0.3.3
  google_sign_in: ^5.4.1
  comment_tree: ^0.3.0
  uuid: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
      - .env
