name: lrf
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  glass: ^1.0.1+1
  expandable: ^5.0.1
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  fade_shimmer: ^2.0.1
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  url_launcher: ^6.1.6
  share_plus: ^4.5.0 
  random_avatar: ^0.0.7
  rounded_loading_button: ^2.1.0
  # firebase_dynamic_links: ^5.0.5
  username_gen: ^1.0.4
  image_picker: ^0.8.6
  firebase_storage: ^11.0.3
  path_provider: ^2.0.11
  image: ^3.2.2
  http: ^0.13.5
  flutter_udid: ^2.0.0 
  firebase_messaging: ^14.0.3
  overlay_support: ^2.0.1

  intl_phone_number_input: ^0.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
      - .env
      - assets/
